// Package codegen translates a Lume AST into Go source code.
//
// The strategy for v0 is straightforward source-to-source: each Lume construct
// has a clean Go counterpart, and we lean on `gofmt` to normalize spacing.
// When we move to a native backend (Cranelift), the AST -> IR pass replaces
// this file but everything upstream stays.
package codegen

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"

	"github.com/mavboas/lume/internal/ast"
)

// Generator holds the state for emitting one Go file.
type Generator struct {
	sb        strings.Builder
	needsFmt  bool
	classDefs map[string]*ast.ClassDecl // populated from file decls before emit
}

// New returns a fresh Generator.
func New() *Generator { return &Generator{} }

// File renders an entire Lume file as Go source. The output is `gofmt`-clean.
// The caller is expected to write this to disk and invoke `go build` on it.
func (g *Generator) File(f *ast.File) (string, error) {
	// Index class declarations so expr() can look up field order and types.
	g.classDefs = map[string]*ast.ClassDecl{}
	for _, d := range f.Decls {
		if cl, ok := d.(*ast.ClassDecl); ok {
			g.classDefs[cl.Name] = cl
		}
	}

	// Emit declarations first into a buffer, since we don't yet know which
	// imports are required.
	var body strings.Builder
	for _, d := range f.Decls {
		switch dd := d.(type) {
		case *ast.ClassDecl:
			body.WriteString(g.classDecl(dd))
			body.WriteString("\n\n")
		case *ast.FnDecl:
			body.WriteString(g.fnDecl(dd))
			body.WriteString("\n\n")
		}
	}

	// Now assemble the full file.
	g.sb.WriteString("// Code generated by lumec. DO NOT EDIT.\n")
	g.sb.WriteString("package main\n\n")
	if g.needsFmt {
		g.sb.WriteString("import \"fmt\"\n\n")
	}
	g.sb.WriteString(body.String())

	formatted, err := format.Source([]byte(g.sb.String()))
	if err != nil {
		// Return the unformatted source too; useful for debugging codegen bugs.
		return g.sb.String(), fmt.Errorf("gofmt failed: %w", err)
	}
	return string(formatted), nil
}

// classDecl emits a Go struct for a Lume class declaration.
func (g *Generator) classDecl(cl *ast.ClassDecl) string {
	var sb strings.Builder
	sb.WriteString("type ")
	sb.WriteString(cl.Name)
	sb.WriteString(" struct {\n")
	for _, f := range cl.Fields {
		sb.WriteString("\t")
		sb.WriteString(goFieldName(f.Name))
		sb.WriteString(" ")
		sb.WriteString(goTypeExpr(f.Type))
		sb.WriteString("\n")
	}
	sb.WriteString("}")
	return sb.String()
}

// goFieldName capitalizes the first letter of a Lume field name for Go.
func goFieldName(name string) string {
	if name == "" {
		return ""
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

func (g *Generator) fnDecl(fn *ast.FnDecl) string {
	var sb strings.Builder
	if fn.Doc != "" {
		for _, line := range strings.Split(fn.Doc, "\n") {
			sb.WriteString("// ")
			sb.WriteString(line)
			sb.WriteString("\n")
		}
	}
	sb.WriteString("func ")
	sb.WriteString(fn.Name)
	sb.WriteString("(")
	for i, p := range fn.Params {
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteString(p.Name)
		sb.WriteString(" ")
		sb.WriteString(goTypeExpr(p.Type))
	}
	sb.WriteString(")")
	if fn.Return != nil {
		sb.WriteString(" ")
		sb.WriteString(goTypeExpr(fn.Return))
	}
	sb.WriteString(" {\n")
	g.block(&sb, fn.Body, fn.Return != nil)
	sb.WriteString("}")
	return sb.String()
}

// block emits a sequence of statements. If returnsValue is true, the LAST
// expression statement is rendered as `return X` so the function returns it.
func (g *Generator) block(sb *strings.Builder, b *ast.Block, returnsValue bool) {
	g.blockWithScope(sb, b, returnsValue, map[string]bool{})
}

func (g *Generator) blockWithScope(sb *strings.Builder, b *ast.Block, returnsValue bool, names map[string]bool) {
	g.blockWithScopeIndent(sb, b, returnsValue, names, "\t")
}

func (g *Generator) blockWithScopeIndent(sb *strings.Builder, b *ast.Block, returnsValue bool, names map[string]bool, indent string) {
	if b == nil {
		return
	}
	last := len(b.Stmts) - 1
	for i, s := range b.Stmts {
		isLast := i == last
		switch ss := s.(type) {
		case *ast.LetStmt:
			sb.WriteString(indent)
			if names[ss.Name] {
				sb.WriteString(ss.Name)
				sb.WriteString(" = ")
			} else {
				names[ss.Name] = true
				if ss.Type != nil {
					sb.WriteString("var ")
					sb.WriteString(ss.Name)
					sb.WriteString(" ")
					sb.WriteString(goTypeExpr(ss.Type))
					sb.WriteString(" = ")
				} else {
					sb.WriteString(ss.Name)
					sb.WriteString(" := ")
				}
			}
			sb.WriteString(g.expr(ss.Value))
			sb.WriteString("\n")
			// Touch the variable so Go doesn't complain about unused locals
			// in the (common) v0 case where the binding isn't read again.
			sb.WriteString(indent)
			sb.WriteString("_ = ")
			sb.WriteString(ss.Name)
			sb.WriteString("\n")
		case *ast.ExprStmt:
			if isLast && returnsValue {
				sb.WriteString(indent)
				sb.WriteString("return ")
				sb.WriteString(g.expr(ss.Expr))
				sb.WriteString("\n")
			} else {
				sb.WriteString(indent)
				sb.WriteString(g.expr(ss.Expr))
				sb.WriteString("\n")
			}
		case *ast.IfStmt:
			// When the if-chain is the final statement of a value-returning
			// function, each branch's last expression must become a return.
			g.ifStmt(sb, ss, isLast && returnsValue, names, indent)
		case *ast.SwitchStmt:
			g.switchStmt(sb, ss, isLast && returnsValue, names, indent)
		case *ast.ForStmt:
			g.forStmt(sb, ss, names, indent)
		}
	}
}

// ifStmt emits `if cond { body } else if ... { } else { }`. When
// branchReturns is true, the body of each branch is rendered with returnValue
// mode so its last expression becomes a return.
func (g *Generator) ifStmt(sb *strings.Builder, s *ast.IfStmt, branchReturns bool, names map[string]bool, indent string) {
	sb.WriteString(indent)
	sb.WriteString("if ")
	sb.WriteString(g.expr(s.Cond))
	sb.WriteString(" {\n")
	g.blockWithScopeIndent(sb, s.Body, branchReturns, cloneNames(names), indent+"\t")
	sb.WriteString(indent)
	sb.WriteString("}")
	for _, e := range s.Elsifs {
		sb.WriteString(" else if ")
		sb.WriteString(g.expr(e.Cond))
		sb.WriteString(" {\n")
		g.blockWithScopeIndent(sb, e.Body, branchReturns, cloneNames(names), indent+"\t")
		sb.WriteString(indent)
		sb.WriteString("}")
	}
	if s.Else != nil {
		sb.WriteString(" else {\n")
		g.blockWithScopeIndent(sb, s.Else, branchReturns, cloneNames(names), indent+"\t")
		sb.WriteString(indent)
		sb.WriteString("}")
	}
	sb.WriteString("\n")
}

func (g *Generator) switchStmt(sb *strings.Builder, s *ast.SwitchStmt, branchReturns bool, names map[string]bool, indent string) {
	sb.WriteString(indent)
	sb.WriteString("switch ")
	sb.WriteString(g.expr(s.Value))
	sb.WriteString(" {\n")
	for _, branch := range s.Cases {
		sb.WriteString(indent)
		sb.WriteString("case ")
		sb.WriteString(g.expr(branch.Value))
		sb.WriteString(":\n")
		g.blockWithScopeIndent(sb, branch.Body, branchReturns, cloneNames(names), indent+"\t")
	}
	if s.Default != nil {
		sb.WriteString(indent)
		sb.WriteString("default:\n")
		g.blockWithScopeIndent(sb, s.Default, branchReturns, cloneNames(names), indent+"\t")
	}
	sb.WriteString(indent)
	sb.WriteString("}\n")
}

func (g *Generator) forStmt(sb *strings.Builder, s *ast.ForStmt, names map[string]bool, indent string) {
	sb.WriteString(indent)
	switch target := s.Target.(type) {
	case *ast.RangeExpr:
		sb.WriteString("for ")
		sb.WriteString(s.Var)
		sb.WriteString(" := ")
		sb.WriteString(g.expr(target.From))
		sb.WriteString("; ")
		sb.WriteString(s.Var)
		sb.WriteString(" < ")
		sb.WriteString(g.expr(target.To))
		sb.WriteString("; ")
		sb.WriteString(s.Var)
		sb.WriteString("++ {\n")
	default:
		sb.WriteString("for _, ")
		sb.WriteString(s.Var)
		sb.WriteString(" := range ")
		sb.WriteString(g.expr(s.Target))
		sb.WriteString(" {\n")
	}
	loopNames := cloneNames(names)
	loopNames[s.Var] = true
	g.blockWithScopeIndent(sb, s.Body, false, loopNames, indent+"\t")
	sb.WriteString(indent)
	sb.WriteString("}\n")
}

func cloneNames(in map[string]bool) map[string]bool {
	out := make(map[string]bool, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}

func (g *Generator) expr(e ast.Expr) string {
	switch ee := e.(type) {
	case *ast.IntLit:
		return fmt.Sprintf("int64(%d)", ee.Value)
	case *ast.DecLit:
		return strconv.FormatFloat(ee.Value, 'g', -1, 64)
	case *ast.StrLit:
		return strconvQuote(ee.Value)
	case *ast.InterpolatedStr:
		return g.interpolatedStr(ee)
	case *ast.BoolLit:
		if ee.Value {
			return "true"
		}
		return "false"
	case *ast.NoneLit:
		return "nil"
	case *ast.ListLit:
		return g.listLit(ee)
	case *ast.ObjLit:
		return g.objLit(ee)
	case *ast.Ident:
		return ee.Name
	case *ast.FieldExpr:
		return g.fieldExpr(ee)
	case *ast.BinaryExpr:
		return "(" + g.expr(ee.Left) + " " + ee.Op + " " + g.expr(ee.Right) + ")"
	case *ast.RangeExpr:
		return "/* range expression */ nil"
	case *ast.UnaryExpr:
		return "(" + ee.Op + g.expr(ee.Sub) + ")"
	case *ast.CallExpr:
		return g.call(ee)
	case *ast.LetExpr:
		return g.letExpr(ee)
	case *ast.MatchExpr:
		return g.matchExpr(ee)
	}
	return "/* TODO unhandled expr */ nil"
}

func (g *Generator) letExpr(e *ast.LetExpr) string {
	var sb strings.Builder
	sb.WriteString("func() ")
	sb.WriteString(goTypeName(e.ResolvedType))
	sb.WriteString(" {\n")
	names := map[string]bool{}
	for _, b := range e.Bindings {
		names[b.Name] = true
		sb.WriteString("\t")
		sb.WriteString(b.Name)
		sb.WriteString(" := ")
		sb.WriteString(g.expr(b.Value))
		sb.WriteString("\n\t_ = ")
		sb.WriteString(b.Name)
		sb.WriteString("\n")
	}
	returnsValue := e.ResolvedType != "" && e.ResolvedType != "none"
	g.blockWithScopeIndent(&sb, e.Body, returnsValue, names, "\t")
	if !returnsValue {
		sb.WriteString("\treturn nil\n")
	}
	sb.WriteString("}()")
	return sb.String()
}

func (g *Generator) matchExpr(e *ast.MatchExpr) string {
	var sb strings.Builder
	sb.WriteString("func() ")
	sb.WriteString(goTypeName(e.ResolvedType))
	sb.WriteString(" {\n")
	sb.WriteString("\t__match := ")
	sb.WriteString(g.expr(e.Value))
	sb.WriteString("\n")
	sb.WriteString("\tswitch __match {\n")
	for _, c := range e.Cases {
		switch p := c.Pattern.(type) {
		case *ast.LiteralPattern:
			sb.WriteString("\tcase ")
			sb.WriteString(g.expr(p.Value))
			sb.WriteString(":\n")
			g.blockWithScopeIndent(&sb, c.Body, e.ResolvedType != "none", map[string]bool{}, "\t\t")
			if e.ResolvedType == "none" {
				sb.WriteString("\t\treturn nil\n")
			}
		case *ast.WildcardPattern:
			sb.WriteString("\tdefault:\n")
			g.blockWithScopeIndent(&sb, c.Body, e.ResolvedType != "none", map[string]bool{}, "\t\t")
			if e.ResolvedType == "none" {
				sb.WriteString("\t\treturn nil\n")
			}
		case *ast.CapturePattern:
			sb.WriteString("\tdefault:\n")
			sb.WriteString("\t\t")
			sb.WriteString(p.Name)
			sb.WriteString(" := __match\n")
			sb.WriteString("\t\t_ = ")
			sb.WriteString(p.Name)
			sb.WriteString("\n")
			names := map[string]bool{p.Name: true}
			g.blockWithScopeIndent(&sb, c.Body, e.ResolvedType != "none", names, "\t\t")
			if e.ResolvedType == "none" {
				sb.WriteString("\t\treturn nil\n")
			}
		}
	}
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn ")
	sb.WriteString(goZeroValueName(e.ResolvedType))
	sb.WriteString("\n")
	sb.WriteString("}()")
	return sb.String()
}

func (g *Generator) listLit(l *ast.ListLit) string {
	if len(l.Elems) == 0 {
		return "nil"
	}
	elemType := goTypeForExpr(l.Elems[0])
	parts := make([]string, len(l.Elems))
	for i, elem := range l.Elems {
		parts[i] = g.expr(elem)
	}
	return "[]" + elemType + "{" + strings.Join(parts, ", ") + "}"
}

func (g *Generator) objLit(o *ast.ObjLit) string {
	if len(o.Fields) == 0 {
		return "map[string]any{}"
	}
	parts := make([]string, len(o.Fields))
	for i, field := range o.Fields {
		parts[i] = strconvQuote(field.Name) + ": " + g.expr(field.Value)
	}
	return "map[string]any{" + strings.Join(parts, ", ") + "}"
}

func (g *Generator) fieldExpr(e *ast.FieldExpr) string {
	target := g.expr(e.Target)
	if e.TargetIsClass {
		// .keys returns the list of field names as a Go string slice literal.
		if e.Name == "keys" {
			if cl, ok := g.classDefs[e.ResolvedClass]; ok {
				names := make([]string, len(cl.Fields))
				for i, f := range cl.Fields {
					names[i] = strconvQuote(f.Name)
				}
				return "[]string{" + strings.Join(names, ", ") + "}"
			}
		}
		return target + "." + goFieldName(e.Name)
	}
	return target + "[" + strconvQuote(e.Name) + "]"
}

// interpolatedStr emits an InterpolatedStr as fmt.Sprintf("...", args...).
// Literal text has its `%` escaped to `%%` so format directives inside the
// user's string don't accidentally consume an arg.
func (g *Generator) interpolatedStr(s *ast.InterpolatedStr) string {
	g.needsFmt = true
	var fmtBuf strings.Builder
	args := make([]string, 0, len(s.Parts))
	for _, p := range s.Parts {
		if p.IsExpr {
			fmtBuf.WriteString("%v")
			args = append(args, g.expr(p.Expr))
		} else {
			fmtBuf.WriteString(strings.ReplaceAll(p.Lit, "%", "%%"))
		}
	}
	out := "fmt.Sprintf(" + strconvQuote(fmtBuf.String())
	for _, a := range args {
		out += ", " + a
	}
	out += ")"
	return out
}

// call rewrites builtin calls and handles class constructors and .with().
func (g *Generator) call(c *ast.CallExpr) string {
	// Method call on a class instance: instance.with(field= val).
	if fe, ok := c.Fn.(*ast.FieldExpr); ok && fe.TargetIsClass {
		if fe.Name == "with" {
			return g.withCall(fe.Target, fe.ResolvedClass, c.NamedArgs)
		}
	}

	if id, ok := c.Fn.(*ast.Ident); ok {
		switch id.Name {
		case "print":
			g.needsFmt = true
			return "fmt.Println(" + g.argList(c.Args) + ")"
		}
		// Named-arg call: class constructor.
		if len(c.NamedArgs) > 0 {
			if _, isClass := g.classDefs[id.Name]; isClass {
				return g.constructorCall(id.Name, c.NamedArgs)
			}
		}
	}
	return g.expr(c.Fn) + "(" + g.argList(c.Args) + ")"
}

// constructorCall emits a Go struct literal: ClassName{FieldA: val, ...}.
func (g *Generator) constructorCall(className string, args []ast.NamedArg) string {
	parts := make([]string, len(args))
	for i, na := range args {
		parts[i] = goFieldName(na.Name) + ": " + g.expr(na.Value)
	}
	return className + "{" + strings.Join(parts, ", ") + "}"
}

// withCall emits a struct literal that copies all fields from target, overriding the named ones.
func (g *Generator) withCall(target ast.Expr, className string, overrides []ast.NamedArg) string {
	cl, ok := g.classDefs[className]
	if !ok {
		return "/* unknown class in .with() */"
	}
	targetStr := g.expr(target)
	overrideMap := map[string]string{}
	for _, na := range overrides {
		overrideMap[na.Name] = g.expr(na.Value)
	}
	parts := make([]string, len(cl.Fields))
	for i, f := range cl.Fields {
		goName := goFieldName(f.Name)
		if val, ok := overrideMap[f.Name]; ok {
			parts[i] = goName + ": " + val
		} else {
			parts[i] = goName + ": " + targetStr + "." + goName
		}
	}
	return className + "{" + strings.Join(parts, ", ") + "}"
}

func (g *Generator) argList(args []ast.Expr) string {
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = g.expr(a)
	}
	return strings.Join(parts, ", ")
}

// ---- type mapping ----

func goTypeExpr(t *ast.TypeExpr) string {
	if t == nil {
		return ""
	}
	if t.Name == "list" && len(t.Args) == 1 {
		return "[]" + goTypeExpr(t.Args[0])
	}
	switch t.Name {
	case "int":
		return "int64"
	case "dec":
		return "float64"
	case "str":
		return "string"
	case "bool":
		return "bool"
	case "obj":
		return "map[string]any"
	case "":
		return ""
	}
	return t.Name
}

func goTypeForExpr(e ast.Expr) string {
	switch e.(type) {
	case *ast.IntLit:
		return "int64"
	case *ast.DecLit:
		return "float64"
	case *ast.StrLit, *ast.InterpolatedStr:
		return "string"
	case *ast.BoolLit:
		return "bool"
	case *ast.ObjLit:
		return "map[string]any"
	case *ast.ListLit:
		return "any"
	default:
		return "any"
	}
}

func goTypeName(name string) string {
	switch name {
	case "", "<unknown>", "none", "<invalid>":
		return "any"
	case "int":
		return "int64"
	case "dec":
		return "float64"
	case "str":
		return "string"
	case "bool":
		return "bool"
	case "obj":
		return "map[string]any"
	}
	if strings.HasPrefix(name, "list[") && strings.HasSuffix(name, "]") {
		elem := strings.TrimSuffix(strings.TrimPrefix(name, "list["), "]")
		return "[]" + goTypeName(elem)
	}
	return name
}

func goZeroValueName(name string) string {
	switch name {
	case "int":
		return "0"
	case "dec":
		return "0"
	case "str":
		return `""`
	case "bool":
		return "false"
	case "none", "", "<unknown>", "<invalid>", "obj":
		return "nil"
	}
	if strings.HasPrefix(name, "list[") {
		return "nil"
	}
	return name + "{}"
}

// strconvQuote returns a Go-quoted string literal for s.
func strconvQuote(s string) string {
	var sb strings.Builder
	sb.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			sb.WriteString(`\"`)
		case '\\':
			sb.WriteString(`\\`)
		case '\n':
			sb.WriteString(`\n`)
		case '\t':
			sb.WriteString(`\t`)
		case '\r':
			sb.WriteString(`\r`)
		default:
			sb.WriteRune(r)
		}
	}
	sb.WriteByte('"')
	return sb.String()
}
